apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: angular
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - image: jhonni1000/paymart-angular:v1
          name: client
          ports:
            - containerPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  ports:
    - name: "4200"
      port: 4200
      targetPort: 4200
  selector:
    app: angular
status:
  loadBalancer: {}
