apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java
  name: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - image: jhonni1000/paymart-java:v1
          name: webapi
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: webapi
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    app: java
status:
  loadBalancer: {}
