apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-dep
  labels:
    app: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - name: java
          image: jhonni1000/paymart-java:v1
          ports:
            - containerPort: 9000
              protocol: TCP
      initContainers:
        - name: init-mysql
          image: busybox
          command: ['sh', 'c', 'until nslookup mysql; do echo waiting for mydb; sleep 2; done;']