apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb-dep
  name: emongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-dep
  template:
    metadata:
      labels:
        app: mongodb-dep
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: epoc
          image: mongo:4
          name: emongo
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: emongo
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb-dep
status:
  loadBalancer: {}

