apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysqldb-dep
  name: emartdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb-dep
  template:
    metadata:
      labels:
        app: mysqldb-dep
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: books
            - name: MYSQL_ROOT_PASSWORD
              value: emartdbpass
          image: mysql:5.7
          name: emartdb
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: emartdb
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: mysqldb-dep
status:
  loadBalancer: {}