apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-dep
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node
          image: jhonni1000/paymart-node:v1
          ports:
            - containerPort: 5000
              protocol: TCP
      initContainers:
         - name: init-mongo
           image: busybox:1.28
           command: ['sh', '-c', 'until nslookup mongodb-svc; do echo waiitng for mongo; sleep 2; done' ]
            
      
    