apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-app
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  strategy: {}
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - image: jhonni1000/paymart-node:v1
          name: api
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: node-app
status:
  loadBalancer: {}
